# Generated by Django 3.0.14 on 2022-05-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'db_table': 'categorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InstAddresses',
            fields=[
                ('addr_id', models.AutoField(primary_key=True, serialize=False)),
                ('addr_zipcode', models.CharField(blank=True, max_length=8, null=True)),
                ('addr_street', models.CharField(blank=True, max_length=100, null=True)),
                ('addr_number', models.CharField(blank=True, max_length=50, null=True)),
                ('addr_complement', models.CharField(blank=True, max_length=100, null=True)),
                ('addr_district', models.CharField(blank=True, max_length=100, null=True)),
                ('addr_city', models.CharField(blank=True, max_length=100, null=True)),
                ('addr_state', models.CharField(blank=True, max_length=100, null=True)),
                ('addr_country', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'inst_addresses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InstBankAccounts',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account_ag', models.CharField(blank=True, max_length=8, null=True)),
                ('bank_account_conta', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account_type', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inst_bank_accounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InstBankPix',
            fields=[
                ('pix_id', models.AutoField(primary_key=True, serialize=False)),
                ('pix_key', models.CharField(blank=True, max_length=100, null=True)),
                ('qrcode_file', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'inst_bank_pix',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InstContacts',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_comercial', models.CharField(blank=True, max_length=11, null=True)),
                ('contact_mobile', models.CharField(blank=True, max_length=12, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_site', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_linkedin', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_youtube', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'inst_contacts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instituicoes',
            fields=[
                ('inst_id', models.AutoField(primary_key=True, serialize=False)),
                ('inst_name', models.CharField(blank=True, max_length=255, null=True)),
                ('inst_cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('logo', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('alt_logo', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'instituicoes',
                'managed': False,
            },
        ),
    ]
