# Generated by Django 3.0.14 on 2022-05-16 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorias',
            options={'managed': False, 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='instaddresses',
            options={'managed': False, 'verbose_name': 'Endereço', 'verbose_name_plural': 'Endereços'},
        ),
        migrations.AlterModelOptions(
            name='instbankaccounts',
            options={'managed': False, 'verbose_name': 'Conta Bancária', 'verbose_name_plural': 'Contas Bancárias'},
        ),
        migrations.AlterModelOptions(
            name='instbankpix',
            options={'managed': False, 'verbose_name': 'Pix', 'verbose_name_plural': 'Pix'},
        ),
        migrations.AlterModelOptions(
            name='instcontacts',
            options={'managed': False, 'verbose_name': 'Contato', 'verbose_name_plural': 'Contatos'},
        ),
        migrations.AlterModelOptions(
            name='instituicoes',
            options={'managed': False, 'verbose_name': 'Instituição', 'verbose_name_plural': 'Instituições'},
        ),
    ]
